# Generated by Django 4.2.9 on 2024-01-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
