# Generated by Django 4.2.9 on 2024-01-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
